name = "dewify-test"
main = "worker.js"
compatibility_date = "2026-09-27"
workers_dev = true

[vars]
RESEND_FROM = "digitalproducts@dewify.shop"
[[d1_databases]]
binding = "DB"
database_name = "dewify-test-db"
database_id = "acf62d71-5031-4dde-b697-0610cd7a8d15"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = true

[[routes]]
pattern = "digitalproducts.dewify.shop"
custom_domain = true
